version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel_app
        volumes:
            - ./:/var/www
        networks:
            - laravel-network

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "10000:80" # Ensure this is correctly mapping to the right port

        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge
